### ISSUE TITLE
benchmarks for comparison

### ISSUE THREAD

**Issue by liangdzou** [MaiaVictor/Symmetric-Interaction-Calculus#2]
I think it will grate if there is a list of benchmarks to show the advantage compared to existing languages/platforms, such as Solidity/EVM, Haskell, etc. For example, some parallel example that cannot be easily implemented in blockchain because it is hard to eliminate non-deterministic behaviour caused by data race.

The paper https://medium.com/@maiavictor/the-abstract-calculus-fe8c46bcf39c is very good, but simple examples can be more intuitive and be more convincible. Some simple examples will be easier for me to convince my boss. :-)

**Comment by VictorTaelin** [comment]
Sorry for the delay, thanks for the interest! [Here](https://github.com/MaiaVictor/Formality/tree/master/examples) are two micro benchmarks where SIC beats Haskell by a large margin (asymptotically) in identical algorithms. More complex examples will come, but I'm focused in other problems right now...
