### ISSUE TITLE
Error in rewrite implementation

### ISSUE THREAD

**Issue by emturner** [MaiaVictor/Symmetric-Interaction-Calculus#5]
In net::rewrite, when kinds are the same, x slot 1 is linked to y slot 1 and x slot 2 is linked to y slot 2.  Shouldn't this be the other way round for symmetric interaction combinators?  So x1 <-> y2 and x2 <-> y1?

**Comment by VictorTaelin** [comment]
No, slot 1 should be linked to slot 1 and slot 2 to slot 2 as far as I understand. Why exactly do you think it should be otherwise?

**Comment by emturner** [comment]
OMG I'm so sorry, got the diagram completely the wrong way round in my head
